### ISSUE TITLE
emily-spring-boot-common dependency 

### ISSUE THREAD

**Issue by dogyy0119** [mingyang66/EmilyGateway#1]
<dependency>
            <groupId>com.emily.infrastructure</groupId>
            <artifactId>emily-spring-boot-common</artifactId>
            <version>${emily.infrastructure.version}</version>
        </dependency>

this dependency  can't  download.

**Comment by mingyang66** [comment]
dependency can't download emily-spring-boot-common has resolved,Replace with other open source packages
